### ISSUE TITLE
Ffmpeg packages not being built as shared libraries

### ISSUE THREAD

**Issue by rajat2004** [rsnk96/Ubuntu-Setup-Scripts#17]
The current ffmpeg build fails due to ```libaom``` not being built as a shared library. The error from the Travis build can be seen below
![libaom_error](https://user-images.githubusercontent.com/37938604/55469598-70556700-5623-11e9-8485-4f336224e550.png)

This is occurring due to the ```av1``` library being built using cmake rather than using ```./configure``` which the ```opencvdirectinstall.sh``` script handles by using ```sed``` to enable building a shared object file.

This might be problem for other packages- ```vid_stab``` and ```x265``` which are also using CMake

**Comment by rsnk96** [comment]
Building of `vid_stab` and `x265` as shared libraries is addressed [here](https://github.com/rsnk96/Ubuntu-Setup-Scripts/commit/8cf27c1dcfae60674dd7aaf41fe4ece8cbe76fc9)
