### ISSUE TITLE
`opencvDirectInstall.sh` upgrades

### ISSUE THREAD

**Issue by rsnk96** [rsnk96/Ubuntu-Setup-Scripts#19]
* [ ] Make opencv use the compiled ffmpeg rather than the one in the system
* [ ] Build opencv with GStreamer

**Comment by rajat2004** [comment]
Not sure if the following would come under upgrades or if they are even required but just adding here

Cmake Warnings and errors
1. Atlas & OpenBLAS errors
![image](https://user-images.githubusercontent.com/37938604/55545832-b0801c80-56eb-11e9-8af3-70b6f75214d8.png)

The packages are being downloaded 
https://github.com/rsnk96/Ubuntu-Setup-Scripts/blob/e0718a5062ff5208a3244dfada6031b58bb11895/opencvDirectInstall.sh#L53

2. VTK error
![image](https://user-images.githubusercontent.com/37938604/55546088-300deb80-56ec-11e9-9f66-d4ed673379f2.png)

Right now, building opencv with VTK is commented out, but will be a problem if someone requires it.

**Comment by rsnk96** [comment]
Indeed @rajat2004 . Can you make this a separate issue?

**Comment by rajat2004** [comment]
@rsnk96 Done
