### ISSUE TITLE
GenSoftware: vmg not present in Ubuntu repos 

### ISSUE THREAD

**Issue by rajat2004** [rsnk96/Ubuntu-Setup-Scripts#25]
```2-GenSoftware.sh``` installs ```vmg``` which is not present in the Ubuntu repositories. For installing vmg, the tar file has to be downloaded from
[https://liquidtelecom.dl.sourceforge.net/project/magnifier/magnifier%20for%20Linux/3.5/magnifier-linux-3.5.tar.bz2](https://liquidtelecom.dl.sourceforge.net/project/magnifier/magnifier%20for%20Linux/3.5/magnifier-linux-3.5.tar.bz2)

This is a very old version, last updated in 2011.
There are alternatives such as ```kmag``` which is present in the Ubuntu repos.

**Comment by rsnk96** [comment]
`kmag` seems to install a lot of `libk*` libraries and seems unnecessarily bloated. For now I'll just add a condition to install it if version >17
