### ISSUE TITLE
execute function does not catch errors

### ISSUE THREAD

**Issue by aswinkumar1999** [rsnk96/Ubuntu-Setup-Scripts#30]
The execute function neatens out the output but makes catching errors a nightmare

**Comment by rsnk96** [comment]
Agreed this can happen. Any place where you're facing it in particular right now? It is supposed to print the error (which is redirected to stdout via `2>&1`, and the output of stdout in turn is stored in the variable `$OUTPUT`)

**Comment by rajat2004** [comment]
I have been thinking about this, not exactly about the errors but about making it easier to see the progress of the installation.
Maybe the bigger downloads such as Anaconda & cloning of OpenCV can be excluded from `execute`
When the download speed is slow, it seems like the script is stuck.
What's your view on this @rsnk96?

**Comment by rsnk96** [comment]
That'd be a good idea for steps which take a lot of time @rajat2004

**Comment by rajat2004** [comment]
@aswinkumar1999 Is there any specific place in the scripts which is not working properly or the `execute` function is not showing the error?

**Comment by aswinkumar1999** [comment]
Yeah , I had the wrong time set in my computer and the `apt update` command couldn't verify the signatures of the fetched packages and exited with `Release File invalid` error which wasn't displayed by the script.

**Comment by rajat2004** [comment]
Ohh, hadn't thought of that since the time and date are generally set by the user while installing Ubuntu itself.
I have no idea why `2&>1` isn't catching this error, something to look into
Until then, maybe we can add a line in the Readme saying to make sure that the system time is correct before running the scripts

**Comment by aswinkumar1999** [comment]
#41 Merged , Closing this issue
