### ISSUE TITLE
ML-Build: Bazel Version for building Tensorflow

### ISSUE THREAD

**Issue by rajat2004** [rsnk96/Ubuntu-Setup-Scripts#32]
Currently, the `ML-Build` script is failing Travis due to unsupported Bazel version
![image](https://user-images.githubusercontent.com/37938604/56263432-8291d380-6100-11e9-986c-76eff5b74142.png)

Specifying the older version during `apt install` doesn't work since the repository only contains the latest bazel version. See this discussion: https://github.com/bazelbuild/continuous-integration/issues/128

Right now, this can be fixed by manual installation of the .deb package with the exact version required by the release.
But this will have to be updated as and when new Tensorflow relases occur

**Comment by rsnk96** [comment]
Fixed thru PR

**Comment by rajat2004** [comment]
`ML-Build.sh` is grabbing a different version of Tensorflow now - `1.12.1` which requires Bazel `0.24.1`.
Should we do something like fix the Tensorflow version depending on the most stable one and fix Bazel also for that?

Or maybe see if it's possible to parse some file in the Tensorflow repo and download the Bazel version accordingly

**Comment by rajat2004** [comment]
https://github.com/tensorflow/tensorflow/blob/343ba9424baab34ea4b8c9ae6d73f93e51af9837/configure.py#L1390
This specifies the minimum Bazel version required.
