### ISSUE TITLE
Install more recent version of CMake

### ISSUE THREAD

**Issue by rajat2004** [rsnk96/Ubuntu-Setup-Scripts#34]
Currently, `cmake` is being installed from the Ubuntu repository which for 16.04 installs `3.5.1` which fails to work on certain repos.

Version `3.5.2` can be installed from PPA - `ppa:george-edison55/cmake-3.x`
It's a stable & tested version for xenial and doesn't give any errors.

**Comment by rsnk96** [comment]
Every `ppa` added would lead to an increase in the time `sudo apt-get update` takes every single time it is run. I think it would be better to not add it unless `3.5.1` is really terrible and not working for a lot of builds. Let me know if that's the case @rajat2004 

If need be, one should be able to build cmake from scratch for the latest version, [similar to what is being done](https://github.com/markus-perl/ffmpeg-build-script/blob/98718353a659d31014ab75ecb716a57ae0a16fad/build-ffmpeg#L291) in `opencvDirectInstall.sh` which uses Markus-Perl's `ffmpeg-build-script` (which as of this comment builds `cmake 3.11.1`)

**Comment by rajat2004** [comment]
> Every `ppa` added would lead to an increase in the time `sudo apt-get update` takes every single time it is run. I think it would be better to not add it unless `3.5.1` is really terrible and not working for a lot of builds. Let me know if that's the case @rajat2004

That's a good point. I didn't face any errors until when I was trying to build a simulator. Let's see, if there are any problems while using it for other more common builds then this can be added.

> If need be, one should be able to build cmake from scratch for the latest version, [similar to what is being done](https://github.com/markus-perl/ffmpeg-build-script/blob/98718353a659d31014ab75ecb716a57ae0a16fad/build-ffmpeg#L291) in `opencvDirectInstall.sh` which uses Markus-Perl's `ffmpeg-build-script` (which as of this comment builds `cmake 3.11.1`)

I thought that `cmake` was being built from source somewhere down the line but wasn't able to remember where exactly. I'll maybe have a look into this, see if it's possible to use this instead of the one installed by `apt`

**Comment by rsnk96** [comment]
Okay. Do reopen this if the problem pops up in multiple cases
