### ISSUE TITLE
FeatureRequest: Install SimpleScreenRecorder

### ISSUE THREAD

**Issue by rajat2004** [rsnk96/Ubuntu-Setup-Scripts#35]
[SimpleScreenRecorder](https://www.maartenbaert.be/simplescreenrecorder/) is a powerful, easy-to-use Linux Program with a clean interface.
It's available in the default Ubuntu repos for the newer distros and can be installed from PPA for 16.04 or lower

**Comment by rsnk96** [comment]
A screen recorder would make for a good addition indeed, but I'm not which would be a better option between SimpleScreenRecorder or Kazam

**Comment by rajat2004** [comment]
I just tried out Kazam, it has a cleaner interface but there are no options at all for recording in a different format or any other configurations such as different frame rate, etc.

**Comment by rsnk96** [comment]
Then SimpleScreenRecorder should do!
