### ISSUE TITLE
Zim repo doesnt have Templates folder

### ISSUE THREAD

**Issue by MukundVarmaT** [rsnk96/Ubuntu-Setup-Scripts#59]
In 1-basicsetup.sh line 73  we copy the .zshrc .zlogin and .zimrc from the the templates folder in the repo https://github.com/zimfw/zimfw. However i dont find any such folder in the repo's master branch and is present in another branch called **zsh-5.0** and **zsh-5.2** and hence while running the script it errors out saying that ,zshrc does not exist when we echo some lines on to that file.

**Comment by rajat2004** [comment]
Yes, noticed it this morning, when started a Travis build yesterday night. They did the first release of ZIM about 12 hours ago, with many backwards-incompatible changes. For now, switching to the older branches will work, have started looking into updating BasicSetup.sh

**Comment by MukundVarmaT** [comment]
So zim-5.2 is an older version?
Yeah switching to another branch did work

**Comment by rajat2004** [comment]
Merged https://github.com/rsnk96/Ubuntu-Setup-Scripts/pull/60 for a temporary fix
