### ISSUE TITLE
Avoiding reinstallation of anaconda3 in the first script

### ISSUE THREAD

**Issue by rsnk96** [rsnk96/Ubuntu-Setup-Scripts#67]
Right now, in the first script, anaconda is forcefully re-installed every time the script is run. But this is not being done in the manner it should be ideally (shift the envs in `/opt/anaconda3/envs` to a backup folder, remove the folder and then reinstall it). We should either cleanly do this, or not reinstall anaconda if it is already installed.

@rajat2004  what's your take on which route is better?

**Comment by rajat2004** [comment]
I think not installing it might be better, maybe prompt the user to do it, or else an argument could be added to the script such as `--force-conda-install` to forcefully do the same
There's also a `anaconda-clean` package, which does something similar
Will need to think about it, but both options seem good
