### ISSUE TITLE
Containerize Setup

### ISSUE THREAD

**Issue by rsnk96** [rsnk96/Ubuntu-Setup-Scripts#72]
* Need to containerize the whole setup
* Can consider hosting in [Github's docker registry](https://github.com/features/packages) itself
* Need to setup automated CI/CD for building docker images with every push
* Perhaps can start from https://github.com/NVAITC/ai-lab as a base image (`FROM` tag in `Dockerfile`, and add zsh, etc for setting up development environment

**Comment by rajat2004** [comment]
This will probably require a bit of refactoring of the scripts, maybe pass some env variables to check whether or not to install Anaconda, etc.

**Comment by rsnk96** [comment]
> This will probably require a bit of refactoring of the scripts, maybe pass some env variables to check whether or not to install Anaconda, etc.

These env-vars/flags could also potentially be integrated with #76 , if we decide to go the command line method for making installs optional
