### ISSUE TITLE
Problems with Ubuntu 20.04

### ISSUE THREAD

**Issue by aswinkumar1999** [rsnk96/Ubuntu-Setup-Scripts#87]
I did a clean Install of `Ubuntu 20.04` and ran the scripts, Here are some problems which I faced... 

- Default Version of `gcc` in 20.04  `9.3.0` and `make` failed at 14% building `protobuf` because it expected version 8 or lower. But adding the flag `-D CMAKE_C_COMPILER=/usr/bin/gcc-8 ` compiled it and installed without any errors

- Atom Editor's unofficial repo doesn't have source entries for `20.04`, Alternatively, we can download the `.deb` file from `https://atom.io/download/deb` and install it... 

- `Shutter` cannot be installed for `18.10` and above unless we manually add an unofficial PPA to do it... We can either add the PPA manually or use a try-catch for it...

**Comment by rsnk96** [comment]
> Default Version of gcc in 20.04 9.3.0 and make failed at 14% building protobuf because it expected version 8 or lower. But adding the flag -D CMAKE_C_COMPILER=/usr/bin/gcc-8 compiled it and installed without any errors

Where exactly is this error happening? While building OpenCV or Tensorflow....?

> Atom Editor's unofficial repo doesn't have source entries for 20.04, Alternatively, we can download the .deb file from https://atom.io/download/deb and install it...

That'll be a pain, yes. But hope the atom folks release it in the standard Ubuntu PPA, I think we can wait for a while

> Shutter cannot be installed for 18.10 and above unless we manually add an unofficial PPA to do it... We can either add the PPA manually or use a try-catch for it...

Thanks for the heads up! Shutter is anyways slow, so was thinking of switching to something else. Considering flameshot for now, do you have any thoughts on this?

**Comment by rajat2004** [comment]
I've added entries for 20.04 (Focal) in Travis, and the build - https://travis-ci.com/github/rajat2004/Ubuntu-Setup-Scripts/builds/173787017
Branch - https://github.com/rsnk96/Ubuntu-Setup-Scripts/compare/master...rajat2004:travis

Adding 5 entries doesn't look very clean to me, therefore testing out the Travis build matrix - https://github.com/rsnk96/Ubuntu-Setup-Scripts/compare/master...rajat2004:travis-matrix, but not working right now, only getting 5 builds instead of expected 15
Build - https://travis-ci.com/github/rajat2004/Ubuntu-Setup-Scripts/builds/173785509

**Comment by aswinkumar1999** [comment]
> Where exactly is this error happening? While building OpenCV or Tensorflow....?`

Really sorry for not mentioning that... This happened while building OpenCV.

> That'll be a pain, yes. But hope the atom folks release it in the standard Ubuntu PPA, I think we can wait for a while

Correct me If I'm wrong, but I feel like the following code should do the job 

```bash
# Download the .deb file for atom
wget -O atom.deb https://atom.io/download/deb 
# Install Atom
sudo dpkg -i atom.deb
# Install Atom's dependencies if they are missing
sudo apt-get -f install
```

Also, atom has an official PPA, which is mentioned [here](https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt)

**Comment by rsnk96** [comment]
> Also, atom has an official PPA, which is mentioned here

That sounds like a good idea! I'll push a change with this update

> Correct me If I'm wrong, but I feel like the following code should do the job

Yes! It will work, only catch is to update Atom, you'll have to re-download the `.deb` file. The PPA method will be able to update atom as a part of `sudo apt ...`


I'll integrate these changes in an upcoming PR, let's see if it clears the Travis builds



> therefore testing out the Travis build matrix

Yes, that does look a lot neater, do integrate it whenever you are able to figure it out! For now I've included the not-so-neat alternative in the PR
