### ISSUE TITLE
similar ubuntu setup effort

### ISSUE THREAD

**Issue by ahundt** [rsnk96/Ubuntu-Setup-Scripts#9]
Hey, I maintain a similar repository, though I have some additional robotics focused stuff:
https://github.com/ahundt/robotics_setup

I didn't have anything specific to ask, I just wanted to connect the dots. Good choice of shell with zsh I use that an occasionally https://github.com/xonsh/xonsh :-)

**Comment by rsnk96** [comment]
Hi

xon shell looks interesting. I'll definitely give it a shot sometime soon. Thanks for the suggestion :smile: 

And you have a lot of interesting libraries covered in your scripts. Do you mind if I link some of the files in your repository in perhaps a robotics.sh file? @ahundt

**Comment by ahundt** [comment]
no problem! that's why I used an open license https://github.com/ahundt/robotics_setup/blob/master/LICENSE.txt just follow that, a quick summary is at https://tldrlegal.com/license/apache-license-2.0-(apache-2.0).

Cheers!
