### ISSUE TITLE
Curious about the use of `full-upgrade` over `upgrade`

### ISSUE THREAD

**Issue by aswinkumar1999** [rsnk96/Ubuntu-Setup-Scripts#90]
Any specific reason to go with `full-upgrade` instead of `upgrade` ?  `full-upgrade` broke my CUDA and Driver Installation and created a dependency conflict between NVIDIA Drivers and the CUDA versions and a year earlier broke my ROS Noetic installation as well.

https://github.com/rsnk96/Ubuntu-Setup-Scripts/blob/2979e32d6e85435ee9ec3dffabd86681fd61787b/config_files/bash_aliases#L7

From a bit of Googling, I was able to find the following regarding `full-upgrade`

> full-upgrade (apt-get(8)) performs the function of upgrade but will remove currently installed packages if this is needed to upgrade the system as a whole.

and from another StackOverflow thread 

Command | Upgrade | Install | Remove
-- | -- | -- | --
`apt-get upgrade` | Yes | No | No
`apt upgrade` | Yes | Yes | No
`apt-get dist-upgrade`, `apt full-upgrade` etc. | Yes | Yes | Yes

Wouldn't it be safer to go with `upgrade`?

**Comment by rsnk96** [comment]
Yes, agreed, safer to go with upgrade. Good catch! Do you want to open a PR?

**Comment by aswinkumar1999** [comment]
Opened a PR for the same.

Thanks
